export const INIT_INDEXPAGE_TRIGGERED = "INIT_INDEXPAGE_TRIGGERED";
export const INIT_INDEXPAGE_REQUEST = "INIT_INDEXPAGE_REQUEST";
export const INIT_INDEXPAGE_SUCCESS = "INIT_INDEXPAGE_SUCCESS";
export const INIT_INDEXPAGE_FAILURE = "INIT_INDEXPAGE_FAILURE";

export const INIT_SHOPPAGE_TRIGGERED = "INIT_SHOPPAGE_TRIGGERED";
export const INIT_SHOPPAGE_REQUEST = "INIT_SHOPPAGE_REQUEST";
export const INIT_SHOPPAGE_SUCCESS = "INIT_SHOPPAGE_SUCCESS";
export const INIT_SHOPPAGE_FAILURE = "INIT_SHOPPAGE_FAILURE";

export const INIT_REGPAGE_TRIGGERED = "INIT_REGPAGE_TRIGGERED";
export const INIT_REGPAGE_REQUEST = "INIT_REGPAGE_REQUEST";
export const INIT_REGPAGE_SUCCESS = "INIT_REGPAGE_SUCCESS";
export const INIT_REGPAGE_FAILURE = "INIT_REGPAGE_FAILURE";

export const HEADER_TRIGGERED = "HEADER_TRIGGERED";
export const HEADER_REQUEST = "HEADER_REQUEST";
export const HEADER_SUCCESS = "HEADER_SUCCESS";
export const HEADER_FAILURE = "HEADER_FAILURE";

export const PURCHASE_SUBMITTED = "PURCHASE_SUBMITTED";
export const PURCHASE_REQUEST = "PURCHASE_REQUEST";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILURE = "PURCHASE_FAILURE";

export const REVIEW_SUBMITTED = "REVIEW_SUBMITTED";
export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_FAILURE = "REVIEW_FAILURE";

export const ENROLLMENT_SUBMITTED = "ENROLLMENT_SUBMITTED";
export const ENROLLMENT_REQUEST = "ENROLLMENT_REQUEST";
export const ENROLLMENT_SUCCESS = "ENROLLMENT_SUCCESS";
export const ENROLLMENT_FAILURE = "ENROLLMENT_FAILURE";
